spring:
  application:
    name: QuickSells

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  config:
    import: optional:file:.env[.env]


management:
  endpoints:
    web:
      exposure:
        include: ["prometheus", "health"]