version: '3'

services:
# Prometheus 설정
 prometheus:
  image: prom/prometheus
  container_name: prometheus
  volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  ports:
    - "9090:9090"
  networks:
    - monitoring

# Grafana 설정
 grafana:
  image: grafana/grafana
  container_name: grafana
  ports:
    - "3000:3000"
  environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin  # 기본 Grafana 비밀번호 설정
  volumes:
    - grafana_data:/var/lib/grafana
  networks:
    - monitoring

networks:
 monitoring:
  driver: bridge

volumes:
 grafana_data: